config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'arts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :users, only:  [ :show, :new, :create, :edit, :update ] do
  #   resources :arts, only:  [ :index, :new, :create ]
  # end
  resources :arts, only:  [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :bookings, only:  [:new, :create]
  end

  resources :bookings, only: [:show, :edit, :update] do
    resources :reviews, only:  [ :new, :create ]
  end

  resources :reviews, only: :index

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  # validates :title, presence: true
  # validates :artist, presence: true
  # validates :price, presence: true
  # validates :dimensions, presence: true
  # validates :city, presence: true
  has_one_attached :photo
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?

  after_save :load_algolia

  # include AlgoliaSearch
  # algoliasearch do
  #   attributes :city, :title, :artist, :price
  # end

  private

  def load_algolia
    index = Algolia::Index.new('Rentart')
    index.add_object(self)
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews
  belongs_to :user
  belongs_to :art
  # validates :start_date, presence: true
  # validates :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  # validates :title, presence: true
  # validates :description, presence: true
  # validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :arts
  # has_many :arts, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @arts = policy_scope(Art)
    @arts = Art.geocoded # returns arts with coordinates
    @markers = @arts.map do |art|
      {
        lat: art.latitude,
        lng: art.longitude,
        infoWindow: render_to_string(partial: "/arts/info_window", locals: { art: art }),
        image_url: helpers.asset_url('palette.png')
      }
    end
  end

  def show
    @art = Art.find(params[:id])
    @booking = @art.bookings.where(user: current_user).last
    # @review = Review.new
    # authorize @booking
    authorize @art
  end

  def new
    @art = Art.new
    authorize @art
  end

  def create
    @art = Art.new(art_params)
    @art.user = current_user
    authorize @art

    if @art.save!
      redirect_to art_path(@art)
    else
      render :new
    end
  end

  def edit
    @art = Art.find(params[:id])
    authorize @art
  end

  def update
    @art = Art.find(params[:id])
    authorize @art
    @art.update(art_params)
    redirect_to art_path(@art)
  end

  def destroy
    @art = Art.find(params[:id])
    authorize @art
    @art.destroy
    redirect_to arts_path
  end

  private

  def art_params
    params.require(:art).permit(:user_id, :title, :artist, :description, :price, :city, :longitude, :latitude, :dimensions, :photo, :rating)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @booking = Booking.find(params[:id])
    @review = Review.new
    authorize @booking
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    # @booking = Booking.new(params[:id])
    @booking = Booking.find(booking_params)
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit

  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :confirmation)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @review = Review.new
    @review.booking = Booking.find(params[:booking_id])
    @review.user = current_user
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = Booking.find(params[:booking_id])
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :description, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @booking = Booking.new
    @art = Art.new
    authorize @user
  end

  # COMMENTED OUT BECAUSE DEVISE TAKES OVER
  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(user_params)
  #   @user.user = current_user
  #   authorize @user
  #   if @user.save
  #     redirect_to new_user_session_path(@user)
  #   else
  #     render :new
  #   end
  # end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # def update
  #   @user = User.find(params[:id])
  #   @user.update(user_params)
  #   authorize @user
  #   redirect_to users_show_path(@user)
  # end

  # private

  # def user_params
  #   params.require(:user).permit(:full_name, :email, :password)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/arts/_booking.html.erb
<%= simple_form_for [@art, @booking] do |f| %>
  <%= f.text_field :start_date, class: 'form-control',  data:{ provide:'datepicker' } %>
  <%= f.text_field :end_date, class: 'form-control',  data:{ provide:'datepicker' } %>
  <%= f.submit "Rent", class: "btn btn-create" %>
<% end %>

app/views/arts/_cards.html.erb
<div class="cards">
  <% @arts.each do |art| %>
    <%= link_to art_path(art) do %>
    <div data-key="<%= art.photo.key %>" class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path art.photo.key, crop: :fill if art.photo.attached? %>')">
        <h2><%= art.title %></h2>
    </div>
    <% end %>
  <% end %>


<!--   <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1549887552-cb1071d3e5ca?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=701&q=80)">
    Naked people
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1561839561-b13bcfe95249?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=627&q=80)">
    Naked people
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1565969645396-e979bdc491b2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1056&q=80)">
    Naked people
  </div>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1562095862-74d923a076e4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80)">
    Naked people
  </div> -->
</div>

app/views/arts/_info_window.html.erb
<%= art.photo %>
<h2><%= art.artist %></h2>
<h3><%= art.title %></h3>
<p><%= art.description %></p>

app/views/arts/_ratingtemp.html.erb
<!-- to fix, we need to iterate, as we have many reviews -->
<% if art.bookings.first.rating.nil? %>
  <p>-</p>
<% else %>
  <p><%=  art.bookings.first.rating %></p>

app/views/arts/_review.html.erb
<% if @art.description.nil? == false %></p>
    <p><%= @art.description %></p>
  <% end %>
  <p>Dimensions: <%= @art.dimensions %></p>

  <h3>Reviews</h3>
  <% if @art.bookings.empty? %>
    <p>This piece of art hasn't been rented yet.</p>
  <% else %>
    <ul class="list-group">
      <% @art.bookings.reviews.each do |review| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <span class="badge badge-primary badge-pill">
            <% counter = 0 %>
            <% 5.times do %>
              <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
              <% counter += 1 %>
            <% end %>
          </span>
          <%= review.description %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <div class="lined-buttons">
    <%= link_to "Edit", edit_art_path , class: "btn-navigation" %>
    <%= link_to "Delete", art_path(@art), class: "btn-navigation", method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
    <!-- <a class="btn-navigation">Delete</a> -->
</div>

app/views/arts/create.html.erb
<h1>Arts#create</h1>
<p>Find me in app/views/arts/create.html.erb</p>

app/views/arts/edit.html.erb
<div class="container-new-edit">
  <%= simple_form_for [@art] do |f| %>
    <%= f.input :title %>
    <%= f.input :artist %>
    <%= f.input :description %>
    <%= f.input :dimensions, label: "Dimensions - (width cm) x (hight cm)" %>
    <%= f.input :city %>
    <%= f.input :price, label: "Price ($) per month"%>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Save", class: "btn-navigation" %>
  <% end %>
</div>

app/views/arts/index.html.erb
<div class="background">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1482245294234-b3f2f8d5f1a4?ixlib=rb-1.2.1&auto=format&fit=crop&w=1130&q=80)">
    <div class="banner-content">
      <h1>Rent art</h1>
      <p>Make your home unique.</p>
      <% if user_signed_in? %>
        <%= link_to "Add art", new_art_path , class: "btn-banner" %>
      <% else %>
        <%= link_to "Rent now", new_user_registration_path , class: "btn-banner" %>
      <% end %>
    </div>
  </div>


  <div class="card-map-division">

    <div class="cart-subdivision">
      <%= render "cards" %>
    </div>

    <div
      id="map"
      style="width: 100%;
      height: 600px;"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      data-markers="<%= @markers.to_json %>"
    ></div>

  </div>

 </div> <!-- class="mapboxgl-popup" -->

app/views/arts/new.html.erb
<div class="container-new-edit">
  <%= simple_form_for @art do |f| %>
    <%= f.input :title %>
    <%= f.input :artist %>
    <%= f.input :description %>
    <%= f.input :dimensions, label: "Dimensions - (width cm) x (hight cm)" %>
    <%= f.input :city %>
    <%= f.input :price, label: "Price ($) per month" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Save", class: "btn-navigation" %>
  <% end %>
</div>

app/views/arts/show.html.erb
<div class="container-show">
  <div class="show-box">

    <div class="show-box-info">
      <h1><%= @art.title %></h1>
      <h2><%= @art.artist %></h2>
      <p> Price per month: £<%= @art.price %></p>
      <% if @art.description.nil? == false %></p>
        <p><%= @art.description %></p>
      <% end %>
      <p>Dimensions (in cm): <%= @art.dimensions %>
        <br><br>
      <%= link_to "Edit", edit_art_path , class: "btn-navigation" %>
      <%= link_to "Delete", art_path(@art), class: "btn-navigation", method: :delete, data: { confirm: "Are you sure?" } %>
      <%= link_to "Book", arts_path, class: "btn-navigation", data: { confirm: "Congratulations, your art will be shipped!" } %>
     </p>
    </div>

    <div class="show-picture">
      <img src="<%= cl_image_path @art.photo.key, crop: :fill if @art.photo.attached? %>" alt="<%= @art.title %>">
    </div>

  </div>


</div>

app/views/arts/update.html.erb
<h1>Arts#update</h1>
<p>Find me in app/views/arts/update.html.erb</p>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<%= simple_form_for @booking do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit "Make booking", class: "btn btn-primary" %>
<% end %>

<%= link_to "Browse through more art", arts_path %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Abel|Cuprum|Nanum+Gothic|Nanum+Myeongjo|News+Cycle|Playfair+Display|Quicksand&display=swap" rel="stylesheet">

    <title>Rentart</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    RentArt | © 2020 RentArt Services, Ltd.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div>
    <a class="navbar-brand" href="/arts">
      <i class="fas fa-palette"></i>
    </a>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= simple_form_for :search, url: root_path, method: :get do |f| %>
            <div class="search-form-control nav-form-group">
              <input class="form-control string required" type="text" name="search[query]" id="search_query" />
              <button name="button" type="submit" class="btn btn-flat">
                <i class="fas fa-search"></i>
              </button>
            </div>
          <% end %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="navbar-brand" href="#">
            <i class="fas fa-envelope"></i>
          </a>
        </li>
        <li class="nav-item dropdown navbar-brand">
          <i class="fas fa-user" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>